### 서울특별시 센터
POST http://localhost:8082/hubs?address=서울특별시 송파구 송파대로 55&hubName=서울특별시 센터

### 경기 북부 센터
POST http://localhost:8082/hubs?address=경기도 고양시 덕양구 권율대로 570&hubName=경기 북부 센터

### 경기 남부 센터
POST http://localhost:8082/hubs?address=경기도 이천시 덕평로 257-21&hubName=경기 남부 센터

### 부산광역시 센터
POST http://localhost:8082/hubs?address=부산 동구 중앙대로 206&hubName=부산광역시 센터

### 대구광역시 센터
POST http://localhost:8082/hubs?address=대구 북구 태평로 161&hubName=대구광역시 센터

### 인천광역시 센터
POST http://localhost:8082/hubs?address=인천 남동구 정각로 29&hubName=인천광역시 센터

### 광주광역시 센터
POST http://localhost:8082/hubs?address=광주 서구 내방로 111&hubName=광주광역시 센터

### 대전광역시 센터
POST http://localhost:8082/hubs?address=대전 서구 둔산로 100&hubName=대전광역시 센터

### 울산광역시 센터
POST http://localhost:8082/hubs?address=울산 남구 중앙로 201&hubName=울산광역시 센터

### 세종특별자치시 센터
POST http://localhost:8082/hubs?address=세종특별자치시 한누리대로 2130&hubName=세종특별자치시 센터

### 강원특별자치도 센터
POST http://localhost:8082/hubs?address=강원특별자치도 춘천시 중앙로 1&hubName=강원특별자치도 센터

### 충청북도 센터
POST http://localhost:8082/hubs?address=충북 청주시 상당구 상당로 82&hubName=충청북도 센터

### 충청남도 센터
POST http://localhost:8082/hubs?address=충남 홍성군 홍북읍 충남대로 21&hubName=충청남도 센터

### 전북특별자치도 센터
POST http://localhost:8082/hubs?address=전북특별자치도 전주시 완산구 효자로 225&hubName=전북특별자치도 센터

### 전라남도 센터
POST http://localhost:8082/hubs?address=전남 무안군 삼향읍 오룡길 1&hubName=전라남도 센터

### 경상북도 센터
POST http://localhost:8082/hubs?address=경북 안동시 풍천면 도청대로 455&hubName=경상북도 센터

### 경상남도 센터
POST http://localhost:8082/hubs?address=경남 창원시 의창구 중앙대로 300&hubName=경상남도 센터

### kakao navi
GET https://apis-navi.kakaomobility.com/v1/directions?origin=127.11015314141542,37.39472714688412&
    destination=127.10824367964793,37.401937080111644&waypoints=&priority=RECOMMEND&car_fuel=GASOLINE&car_hipass=false&
    alternatives=false&road_details=false

### navigate
POST http://localhost:8082/hubs/navigate

### 길찾기
GET http://localhost:8082/hubs/routes?
    startHubName=서울특별시 센터&
    endHubName=강원특별자치도 센터

### 허브 검색
GET http://localhost:19092/hubs?
    name=센터&
    sort=name,desc&
    sort=address,asc&
    size=5

### 허브 단일 조회
GET http://localhost:8082/hubs/7d343d3b-b54c-11ef-a0d4-0242ac120002

### 허브 수정
PATCH http://localhost:8082/hubs/7d343d3b-b54c-11ef-a0d4-0242ac120002
Content-Type: application/json

{
  "name": "경기 북부 센터",
  "address": "경기도 고양시 덕양구 권율대로 570",
  "isDelete": false
}