create table hub
(
    id         binary(16)   not null
        primary key,
    name       varchar(255) not null,
    address    varchar(255) not null,
    longitude  double       not null,
    latitude   double       not null,
    manager    varchar(255) not null,
    is_delete  bit          not null,
    is_public  bit          not null,
    created_at datetime(6)  null,
    created_by binary(16)   null,
    updated_at datetime(6)  null,
    updated_by binary(16)   null,
    deleted_at datetime(6)  null,
    deleted_by binary(16)   null
);

create table hub_route
(
    id               binary(16)  not null
        primary key,
    start_hub_id     binary(16)  null,
    end_hub_id       binary(16)  null,
    estimated_meter  double      null,
    estimated_second double      null,
    is_delete        bit         not null,
    is_public        bit         not null,
    created_at       datetime(6) null,
    created_by       binary(16)  null,
    updated_at       datetime(6) null,
    updated_by       binary(16)  null,
    deleted_at       datetime(6) null,
    deleted_by       binary(16)  null,
    constraint FKiwko4kn019iy8sui0lwuhvu8n
        foreign key (end_hub_id) references hub (id),
    constraint FKsppx1a19msk4e507me0bqs8l1
        foreign key (start_hub_id) references hub (id)
);

INSERT INTO hub (id,
                 name,
                 address,
                 latitude,
                 longitude,
                 is_delete,
                 is_public,
                 created_at,
                 created_by,
                 updated_at,
                 updated_by,
                 deleted_at,
                 deleted_by)
VALUES (UNHEX(REPLACE(UUID(), '-', '')), '경기 북부 센터', '경기도 고양시 덕양구 권율대로 570', 37.6404095, 126.8737802, false, true,
        NOW(), null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '경기 남부 센터', '경기도 이천시 덕평로 257-21', 37.1903115, 127.3760896, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '서울특별시 센터', '서울특별시 송파구 송파대로 55', 37.4969143, 127.1121343, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '부산광역시 센터', '부산 동구 중앙대로 206', 35.11571, 129.0428216, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '대구광역시 센터', '대구 북구 태평로 161', 35.8758026, 128.5959092, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '인천광역시 센터', '인천 남동구 정각로 29', 37.4558148, 126.7062842, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '광주광역시 센터', '광주 서구 내방로 111', 35.1597705, 126.8515218, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '대전광역시 센터', '대전 서구 둔산로 100', 36.3501707, 127.3848389, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '울산광역시 센터', '울산 남구 중앙로 201', 35.5388808, 129.3115449, false, true, NOW(), null,
        NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '세종특별자치시 센터', '세종특별자치시 한누리대로 2130', 36.4799427, 127.289059, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '강원특별자치도 센터', '강원특별자치도 춘천시 중앙로 1', 37.882531, 127.7291452, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '충청북도 센터', '충북 청주시 상당구 상당로 82', 36.6353828, 127.4914807, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '충청남도 센터', '충남 홍성군 홍북읍 충남대로 21', 36.6588409, 126.6736967, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '전북특별자치도 센터', '전북특별자치도 전주시 완산구 효자로 225', 35.8200701, 127.1091229, false, true,
        NOW(), null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '전라남도 센터', '전남 무안군 삼향읍 오룡길 1', 34.8152658, 126.4573699, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '경상북도 센터', '경북 안동시 풍천면 도청대로 455', 36.5753879, 128.5054506, false, true, NOW(),
        null, NOW(), null, null, null),
       (UNHEX(REPLACE(UUID(), '-', '')), '경상남도 센터', '경남 창원시 의창구 중앙대로 300', 35.237101, 128.6912625, false, true, NOW(),
        null, NOW(), null, null, null);