### Create Company
POST http://localhost:19093/companies
Content-Type: application/json

{
  "name": "새 수령업체",
  "type": "RECEIVER",
  "address": "주소임 123",
  "hubId": "7d343cda-b54c-11ef-a0d4-0242ac120002"
}

### Update Company
PATCH http://localhost:19093/companies/363f3275-b285-4bbc-ad2d-3a282f52f3da
Content-Type: application/json

{
  "name": "수정된 수령업체",
  "type": "PRODUCER",
  "address": "수정된 주소임 123"
}

### Get Company
GET http://localhost:19093/companies/363f3275-b285-4bbc-ad2d-3a282f52f3da

### Search Companies
GET http://localhost:19093/companies/search?name=업체&sort=name,desc&sort=address&sort=type,desc&size=5